### ISSUE TITLE
SiteRep for tasks by @heyrandhir

### ISSUE THREAD

**Issue by heyrandhir** [Real-Dev-Squad/skill-tree-backend#74]
# Tasks Completed.
- [x] Worked on GET `/endorsements/:id` endpoint along the unit tests for the same. 
- [x] Worked on the documentation for the repo.

# Tasks Pending
- [ ] writing the integration tests for the GET `/endorsements/:id` endpoint.
